#pragma check_stack(off)
#pragma strict_gs_check(off)
#pragma runtime_checks("", off)

#include <windows.h>
#include <windowsx.h>
#include <dwmapi.h>
#include <shlobj.h>
#include <roapi.h>

#pragma region
typedef struct _UNICODE_STRING
{
  USHORT Length;
  USHORT MaximumLength;
  _Field_size_bytes_part_opt_(MaximumLength, Length) PWCH Buffer;
} UNICODE_STRING, * PUNICODE_STRING;

typedef const UNICODE_STRING* PCUNICODE_STRING;
typedef struct _STRING
{
  USHORT Length;
  USHORT MaximumLength;
  _Field_size_bytes_part_opt_(MaximumLength, Length) PCHAR Buffer;
} STRING, * PSTRING, ANSI_STRING, * PANSI_STRING, OEM_STRING, * POEM_STRING;
typedef struct _RTL_DRIVE_LETTER_CURDIR
{
  USHORT Flags;
  USHORT Length;
  ULONG TimeStamp;
  STRING DosPath;
} RTL_DRIVE_LETTER_CURDIR, * PRTL_DRIVE_LETTER_CURDIR;
typedef struct _CURDIR
{
  UNICODE_STRING DosPath;
  HANDLE Handle;
} CURDIR, * PCURDIR;
#define RTL_MAX_DRIVE_LETTERS 32
typedef struct _CLIENT_ID
{
  HANDLE UniqueProcess;
  HANDLE UniqueThread;
} CLIENT_ID, * PCLIENT_ID;
typedef struct _SECTION_IMAGE_INFORMATION
{
  PVOID TransferAddress;          // The address of the image entry point function.
  ULONG ZeroBits;                 // The number of high-order address bits that must be zero in the image base address.
  SIZE_T MaximumStackSize;        // The maximum stack size of threads from the PE file header.
  SIZE_T CommittedStackSize;      // The initial stack size of threads from the PE file header.
  ULONG SubSystemType;            // The image subsystem from the PE file header (e.g., Windows GUI, Windows CUI, POSIX).
  union
  {
    struct
    {
      USHORT SubSystemMinorVersion;
      USHORT SubSystemMajorVersion;
    };
    ULONG SubSystemVersion;
  };
  union
  {
    struct
    {
      USHORT MajorOperatingSystemVersion;
      USHORT MinorOperatingSystemVersion;
    };
    ULONG OperatingSystemVersion;
  };
  USHORT ImageCharacteristics;    // The image characteristics from the PE file header.
  USHORT DllCharacteristics;      // The DLL characteristics flags (e.g., ASLR, NX compatibility).
  USHORT Machine;                 // The image architecture (e.g., x86, x64, ARM).
  BOOLEAN ImageContainsCode;      // The image contains native executable code.
  union
  {
    UCHAR ImageFlags;
    struct
    {
      UCHAR ComPlusNativeReady : 1;           // The image contains precompiled .NET assembly generated by NGEN (Native Image Generator).
      UCHAR ComPlusILOnly : 1;                // the image contains only Microsoft Intermediate Language (IL) assembly.
      UCHAR ImageDynamicallyRelocated : 1;    // The image was mapped using a random base address rather than the preferred base address.
      UCHAR ImageMappedFlat : 1;              // The image was mapped using a single contiguous region, rather than separate regions for each section.
      UCHAR BaseBelow4gb : 1;                 // The image was mapped using a base address below the 4 GB boundary.
      UCHAR ComPlusPrefer32bit : 1;           // The image prefers to run as a 32-bit process, even on a 64-bit system.
      UCHAR Reserved : 2;
    };
  };
  ULONG LoaderFlags;               // Reserved by ntdll.dll for the Windows loader.
  ULONG ImageFileSize;             // The size of the image, in bytes, including all headers.
  ULONG CheckSum;                  // The image file checksum, from the PE optional header.
} SECTION_IMAGE_INFORMATION, * PSECTION_IMAGE_INFORMATION;
typedef struct _RTL_USER_PROCESS_INFORMATION
{
  ULONG Length;
  HANDLE ProcessHandle;
  HANDLE ThreadHandle;
  CLIENT_ID ClientId;
  SECTION_IMAGE_INFORMATION ImageInformation;
} RTL_USER_PROCESS_INFORMATION, * PRTL_USER_PROCESS_INFORMATION;
typedef struct _RTL_USER_PROCESS_PARAMETERS
{
    ULONG MaximumLength;
    ULONG Length;

    ULONG Flags;
    ULONG DebugFlags;

    HANDLE ConsoleHandle;
    ULONG ConsoleFlags;
    HANDLE StandardInput;
    HANDLE StandardOutput;
    HANDLE StandardError;

    CURDIR CurrentDirectory;
    UNICODE_STRING DllPath;
    UNICODE_STRING ImagePathName;
    UNICODE_STRING CommandLine;
    PVOID Environment;

    ULONG StartingX;
    ULONG StartingY;
    ULONG CountX;
    ULONG CountY;
    ULONG CountCharsX;
    ULONG CountCharsY;
    ULONG FillAttribute;

    ULONG WindowFlags;
    ULONG ShowWindowFlags;
    UNICODE_STRING WindowTitle;
    UNICODE_STRING DesktopInfo;
    UNICODE_STRING ShellInfo;
    UNICODE_STRING RuntimeData;
    RTL_DRIVE_LETTER_CURDIR CurrentDirectories[RTL_MAX_DRIVE_LETTERS];

    ULONG_PTR EnvironmentSize;
    ULONG_PTR EnvironmentVersion;

    PVOID PackageDependencyData;
    ULONG ProcessGroupId;
    ULONG LoaderThreads;
    UNICODE_STRING RedirectionDllName; // REDSTONE4
    UNICODE_STRING HeapPartitionName; // 19H1
    PULONGLONG DefaultThreadpoolCpuSetMasks;
    ULONG DefaultThreadpoolCpuSetMaskCount;
    ULONG DefaultThreadpoolThreadMaximum;
    ULONG HeapMemoryTypeMask; // WIN11
} RTL_USER_PROCESS_PARAMETERS, *PRTL_USER_PROCESS_PARAMETERS;
#pragma endregion


NTSYSAPI
NTSTATUS
NTAPI
RtlCreateUserProcess(
    _In_ PCUNICODE_STRING NtImagePathName,
    _In_ ULONG ExtendedParameters, // HIWORD(NumaNodeNumber), LOWORD(Reserved)
    _In_ PRTL_USER_PROCESS_PARAMETERS ProcessParameters,
    _In_opt_ PSECURITY_DESCRIPTOR ProcessSecurityDescriptor,
    _In_opt_ PSECURITY_DESCRIPTOR ThreadSecurityDescriptor,
    _In_opt_ HANDLE ParentProcess,
    _In_ BOOLEAN InheritHandles,
    _In_opt_ HANDLE DebugPort,
    _In_opt_ HANDLE TokenHandle, // used to be ExceptionPort
    _Out_ PRTL_USER_PROCESS_INFORMATION ProcessInformation
    );

static __forceinline const void* NtCurrentImage(void) // cheese and rice it's jason bourne
{
    return (unsigned short*)*(unsigned char**)((unsigned short*)(*(unsigned char**)((unsigned char*)__readgsqword(0x60) + 0x20) + 0x60) + 0x04);
}

static __forceinline unsigned short NtStartupReserved2(void)
{
    return *(unsigned short*)((unsigned char*)NtCurrentImage() - 0x05A4);
}

static void MsgBox(HWND hwndOwner)
{
  MSGBOXPARAMSW msgbox;
  
  msgbox.cbSize = sizeof(msgbox);
  msgbox.hwndOwner = hwndOwner;
  msgbox.hInstance = GetModuleHandleW(0);
  msgbox.lpszText = L"";
  msgbox.lpszCaption = L"";
  msgbox.dwStyle = MB_APPLMODAL;
  msgbox.lpszIcon = NULL;
  msgbox.dwContextHelpId = 0;
  msgbox.lpfnMsgBoxCallback = NULL;
  msgbox.dwLanguageId = MAKELANGID(LANG_NEUTRAL, SUBLANG_NEUTRAL);

  MessageBoxIndirectW(&msgbox);
}

LRESULT
CALLBACK
WndProcW(
    _In_ HWND hWnd,
    _In_ UINT Msg,
    _In_ WPARAM wParam,
    _In_ LPARAM lParam)
{
    if (Msg == WM_DESTROY)
    {
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProcW(hWnd, Msg, wParam, lParam);
}

  WNDCLASSW wc = { 0 };
static __forceinline HWND DummyWindow(void)
{
    wc.lpfnWndProc = WndProcW;
    wc.hInstance = GetModuleHandleW(0);
    wc.lpszClassName = L"DummyWindowClass";
    wc.hCursor = LoadCursorW(0, IDC_ARROW);
    wc.hIcon = LoadIconW(0, IDI_APPLICATION);
    RegisterClassW(&wc);
    return CreateWindowExW(0, wc.lpszClassName, L"DummyWindow", WS_OVERLAPPEDWINDOW,
      CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT,
      0, 0, wc.hInstance, 0);
}
#pragma pack(1)
typedef struct _SHARED_STARTUP_INFO_W {
  STARTUPINFOEXW StartupInfoEx;
  PROCESS_INFORMATION ProcessInfo;
  unsigned char attributeList[72];
} SHARED_STARTUP_INFO_W, * PSHARED_STARTUP_INFO_W;
#pragma pack()

//#pragma section(".shared", read, write)
//__declspec(allocate(".shared") selectany) SHARED_STARTUP_INFO_W _ = { 0x00 };
#define WHERE_NOONE_CAN_SEE_ME ((int) -32000)
#define WHERE_NOONE_CAN_SEE_ME2 ((int) -3200)
#pragma comment(linker, "/SUBSYSTEM:CONSOLE")
//#pragma comment(linker, "/SUBSYSTEM:WINDOWS")
void __stdcall mainCRTStartup()
//void __stdcall WinMainCRTStartup()
{
    RoInitialize(RO_INIT_MULTITHREADED);
    //RoInitialize(RO_INIT_MULTITHREADED);
    //CoInitializeEx(NULL, COINIT_APARTMENTTHREADED | COINIT_SPEED_OVER_MEMORY | COINIT_DISABLE_OLE1DDE);
    //CoInitializeEx(NULL, COINIT_MULTITHREADED | COINIT_SPEED_OVER_MEMORY | COINIT_DISABLE_OLE1DDE);
    BOOL fDisable = TRUE;
    BOOL fDisable2 = FALSE;
    if (0x00 == NtStartupReserved2())
    {
        SHARED_STARTUP_INFO_W _;
        SecureZeroMemory(&_ , sizeof(_));
        (_.StartupInfoEx.StartupInfo.cb = sizeof(STARTUPINFOW), _.StartupInfoEx.StartupInfo.dwFlags = STARTF_FORCEOFFFEEDBACK,
          !!CreateProcessW(NtCurrentImage(), 0, 0, 0, 0,
            CREATE_NO_WINDOW
            |DETACHED_PROCESS

            | CREATE_NEW_PROCESS_GROUP
            //| CREATE_SUSPENDED
            | CREATE_IGNORE_SYSTEM_DEFAULT
            ,
            0, 0, &_.StartupInfoEx.StartupInfo, &_.ProcessInfo));
        CloseHandle(_.ProcessInfo.hThread);
        CloseHandle(_.ProcessInfo.hProcess);
    }
    else
    {
      //FreeConsole();
      HWND con = GetConsoleWindow();
      
      SetWindowPos(con, HWND_TOPMOST, WHERE_NOONE_CAN_SEE_ME, WHERE_NOONE_CAN_SEE_ME,
        0, 0, SWP_NOSIZE | SWP_NOACTIVATE | SWP_ASYNCWINDOWPOS | SWP_FRAMECHANGED);
      DWORD dwExStyle = GetWindowExStyle(con);
      SetWindowLongPtrW(con, GWL_EXSTYLE, dwExStyle | WS_EX_TOOLWINDOW);
      FreeConsole();
      //FreeConsole();
      // MessageBoxW(0, L"Yay, you re-executed yourself!", NtCurrentImage(), 0);
      //MsgBox();
      HWND dummy = DummyWindow();
      dwExStyle = GetWindowExStyle(dummy);
      SetWindowLongPtrW(dummy, GWL_EXSTYLE, dwExStyle | WS_EX_TOOLWINDOW);
      //DwmSetWindowAttribute(dummy, DWMWA_FORCE_ICONIC_REPRESENTATION, (LPCVOID)&fDisable, sizeof(fDisable));
      DwmSetWindowAttribute(dummy, DWMWA_TRANSITIONS_FORCEDISABLED, (LPCVOID)&fDisable, sizeof(fDisable));
      ShowWindow(dummy, SW_SHOWMINIMIZED);
      SetWindowLongPtrW(dummy, GWL_EXSTYLE, 0);
      SetForegroundWindow(dummy);
      UpdateWindow(dummy);
      DisableProcessWindowsGhosting();
      SetWindowLongPtrW(dummy, GWL_EXSTYLE, dwExStyle);
      ShowWindow(dummy, SW_SHOWNORMAL);
      UpdateWindow(dummy);

      MSG msg;
      while (0 < GetMessage(&msg, 0, 0, 0))
      {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
      }
    }
}
